# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180311_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='headshot',
            field=models.ImageField(default='default.jpg', upload_to='avatar/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
