# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181021_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=models.TextField(blank=True, max_length=10, verbose_name='分类内容'),
        ),
        migrations.AddField(
            model_name='tag',
            name='body',
            field=models.TextField(blank=True, max_length=10, verbose_name='标签内容'),
        ),
    ]
