# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstory', '0007_auto_20181016_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': '城市站发布', 'verbose_name_plural': '城市站发布'},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='城市名称+标题'),
        ),
    ]
